
wallpaper = HDMI-A-1,/home/ricardo/wallpapers/current.jpg 

wallpaper {
    monitor = eDP-1
    path = ~/wallpapers/current.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/wallpapers/current.jpg
}
